apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: products-ingress
spec:
  rules:
    - host: products.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: products-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: products-front
                port:
                  number: 80
